package com.forecast.notification.config;

import io.swagger.v3.oas.models.OpenAPI;
import io.swagger.v3.oas.models.info.Contact;
import io.swagger.v3.oas.models.info.Info;
import io.swagger.v3.oas.models.servers.Server;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

import java.util.List;

@Configuration
public class OpenApiConfig {

    @Bean
    public OpenAPI notificationServiceOpenAPI() {
        return new OpenAPI()
                .info(new Info()
                        .title("Notification Service API")
                        .description("Persists and serves the alert history generated by stock and forecast events. " +
                                "Alerts are created automatically by Kafka consumers — this API is read-only.")
                        .version("v1.0.0")
                        .contact(new Contact().name("Demand Forecast Platform")))
                .servers(List.of(
                        new Server().url("http://localhost:8084").description("Local")
                ));
    }
}
